# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO = /usr/share/arduino
ARDUINO_DIR = $(ARDUINO)
ARDMK_VENDOR = archlinux-arduino
ARCHITECTURE = avr
MCU = atmega328p
BOARD_TAG = nano
AVRDUDE_ARD_BAUDRATE = 57600

include $(ARDUINO)/Arduino.mk
